### ISSUE TITLE
Usage of cron Trigger

### ISSUE THREAD

**Issue by tclass** [thawankeane/nest-inngest#2]
Hey,
nice project, it works really well. I was wondering how to define a cron Trigger. I tried it like this, but it doesn't work because cron is defined as undefined, for some reason. Any pointers what I'm doing wrong?

```
  @AssetSync.Function({
    id: 'assetSync',
    retries: 0,
    concurrency: 1,
  })
  @AssetSync.Trigger({
    event: 'sync',
    cron: '0 9 * * *',
  })
```

**Comment by tclass** [comment]
ok, I'm an idiot, I defined the event name and wanted to define a cron, but I can only define a cron or an event name 
```
  @AssetSync.Trigger({
    cron: '0 9 * * *',
  })
```
this works without a problem.

**Comment by mish0501** [comment]
How did you use `NestInngest.context` when you defined the cron trigger for the type of the handler data?
